### PR TITLE
Fix sparse matrix creation performance issue (#109)

### PR DESCRIPTION
**Pull request by dbalabka**

### CODE REVIEW

**Comment by dbalabka** [comment]
WIP: Level exclusion does not work properly.

**Comment by dbalabka** [comment]
@matthewwardrop, could you please take a look? Changes are ready for review.

**Comment by matthewwardrop** [comment]
Thanks so much for taking the time to try and fix things here @dbalabka ! This implementation definitely needed some love, and your implementation was much faster when there was a large number of levels.

Unfortunately, this patch introduced a few bugs that I fixed, including:
- The order of the columns did not match the order of the levels.
- The shape of the sparse matrix was not specified, and so if the last rows did not have a value that aligned with the encoded levels the output matrix was truncated.

The good news is that I was able to further improve the performance by another ~50% of the already improved performance, so hopefully your use-cases will now be blazingly fast. And although the patch that's hitting main doesn't much resemble your fix, I'll leave your commit in place so you get the credit you deserve!

Thanks again!

**Comment by dbalabka** [comment]
@matthewwardrop, thanks for your time reviewing these changes and code fixes. I've reviewed the adjustment you made to understand where I was wrong, and it seems that these cases weren't covered with tests. Therefore, I've changed the test cases to track the problem's regression. Please see #112

Your performance improvement has the following effect on our data:
Before:
```
CPU times: user 21.2 s, sys: 398 ms, total: 21.6 s
Wall time: 21.7 s
```
After:
```
CPU times: user 17.3 s, sys: 278 ms, total: 17.6 s
Wall time: 17.6 s
```

Thanks for keeping my authorship! 😃

**Pull request merged**
