### PR TITLE
ENH: Add cubic regression spline

### PR DESCRIPTION
**Pull request by bashtage**
Adds both cyclic and natural cubic regression splines, and the operators `cc`, `cr` and `cs`.

Some things to do: 

- [x] Complete test coverage
- [x] Remove legacy patsy classes
- [x] Clean up docs
- [x] Add to formulaic docs
- [x] Fix skipped test

### CODE REVIEW

**Comment by bashtage** [comment]
Some things to do: 

- [ ] Complete test coverage
- [ ] Remove legacy patsy classes
- [ ] Clean up docs
- [ ] Add to formulaic docs

**Comment by matthewwardrop** [comment]
Hi @bashtage! Thank you for these contributions!

These code contributions appear to be lightly modified/repackaged versions of the same code in patsy (including unmodified docstrings) that is licensed under a different license (BSD two-clause vs MIT). These licenses are compatible, but we would still need to respect the terms of that license, which indicated that we need to reproduce the original copyright notice. So far all the implementations in formulaic have been independently written, so I haven't had to worry about the headaches associated with licensing, but if we include this as is then we will have to start caring. I think we can achieve that by just pasting the appropriate license information at the top of the file, and extending the root-level MIT LICENSE with something like "unless otherwise indicated in the source files."

Since this is coming directly from patsy, I'm assuming that it is already battle-tested. If the performance is lacking, I might clean room a replacement at some point... but it largely looks good otherwise to me!

Is this ready for a final review?

**Comment by bashtage** [comment]
It's not ready.  I need to clean up some legacy patsy things that I used to ensure the tests work.  I'll also add the license. 

I might look to simplify the number of functions as well.  Some are very small and only appear in one place.

This, the subset and the constraint parsing are the final pieces to get statsmodels to pass with virtually no modifications to function calls at the API level.

**Comment by matthewwardrop** [comment]
Also, would you mind rebasing this on main. I want to see if that allows the GitHub actions to run on PRs from your fork :).

**Comment by bashtage** [comment]
Rebased and passing now.  It was the Literal import on 3.7.

**Comment by bashtage** [comment]
@matthewwardrop I think this is ready for review. I brought in the key changes from basis spline into how things like extrapolation work.

**Comment by matthewwardrop** [comment]
Hi @bashtage ! Rather than have a tonne of back-and-forth, I took the liberty of pushing some fixes, including fixing some inconsistent documentation (like `cubic_spline` claiming to be `basis_spline`, a missing copyright, and setting `cyclic=False` by default in `cubic_spline`, which is more consistent with my expectations. If these changes all look good to you, I can merge this in. Feel free to push back if any of these changes doesn't make sense to you.

**Comment by bashtage** [comment]
They all sound good.  Not surprised that I missed a few words basis.  Happy
for you to merge.

**Comment by matthewwardrop** [comment]
It's in! Thank you so much for your efforts here!

I'll tag a v1.1 release shortly, certainly by the end of the week. Let me know if anything more crops up!

**Comment by bashtage** [comment]
Thanks for getting this and the other in, as well as writing quite a few that helped sm get across the line.  I'll run it against main and let you know if there are any issues.

**Pull request merged**
