### PR TITLE
ENH: Add pickle support to ModelMatrix and FactorValues

### PR DESCRIPTION
**Pull request by bashtage**
Add `__reduce__ex__` to classes using ObjectProxy
Add tests of equivalence

### CODE REVIEW

**Comment by bashtage** [comment]
`hatch fmt` seems to have gone a bit haywire

**Comment by bashtage** [comment]
Better after running black and a few manual fixes.

**Comment by matthewwardrop** [comment]
Thanks for the patch @bashtage !

I simplified it down a little (just used the class constructors rather than a new method), and fixed some new typing conventions that would have broken in older versions of Python. But otherwise looked good!

Also, for formatting you can use: `hatch run lint:format`. I think hatch added `fmt` functionality after I set this up, so I might need to update it... but I'm eying moving to `uv` too.

**Comment by bashtage** [comment]
3.13 waa the reason for the constructors.  Not sure if this is a bug in 3.13 but tests fail using the obvious reduce style.

**Comment by matthewwardrop** [comment]
Ah! I should have realised you had a reason for this! Sorry! I'll look into this soon.

**Pull request merged**
