### PR TITLE
BUG: Correct parsing multiple hypothesis statements

### PR DESCRIPTION
**Pull request by bashtage**
Correct parsing comma separated hypothesese with more than 2 statements

### CODE REVIEW

**Comment by bashtage** [comment]
This PR has a failing test only now.  I think it should be the case that a constraint like `"a=0, b=1, c=2"` should be equivalent to `{"a":0,"b":1,"c":2}`.  There is something going on with the tokenizing of the single string constraint.

**Comment by matthewwardrop** [comment]
Sorry for the delay. This slipped under my radar!

I've been pummeled by work/life recently, but I'll try to get to this soon and release it with 0.4.0 (along with a bunch of other things coming down the pipeline shortly).

**Comment by bashtage** [comment]
Thanks. I took a look but couldn't quite figure out where to start.  I came to the conclusion that some special parsing might be needed.  For now I wrote a basic reparser that handles this case and turns it into a dictionary of constraints.

**Comment by matthewwardrop** [comment]
Thanks again for surfacing this. Looks like I forgot to handle the merging of tuples at during constraint parsing. I've fixed this in: https://github.com/matthewwardrop/formulaic/commit/577fb0ee0a6a337a2dd404d32860460129d0dc37. Should be released as part of 0.4.0 in the near future. Thanks again @bashtage !

**Comment by bashtage** [comment]
Thanks for the quick fix.

**Pull request closed without merging**
